apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-frontend
  labels:
    app: test-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-frontend
  template:
    metadata:
      labels:
        app: test-frontend
    spec:
      containers:
        - name: test-frontend
          image: pavloskomple/test-frontend:v1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: test-frontend-service
spec:
  selector:
    app: test-frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

